### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [albinario/bwa-u4-feature-request#1]
Meets Expectations

Well done on this feature, it is unique and I've haven't seen this before. The format is well done and caveats was well laid out, I personally could not think of any caveats for this. One thing I would have liked is a more technical aspect on the design section but it's done pretty well. Try to get this implemented, and keep up the good work.

**Comment by albinario** [comment]
Implementation is done, and is sitting in a feature branch in my Jammming repository. Thanks Mike.
